#!/usr/bin/env bash
# Setup haproxy on server lb-01 to serve web-01 and web-02.

sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server web-01 web-01:80 check
        server web-02 web-02:80 check
" | sudo tee /etc/haproxy/haproxy.cfg  # Overwriting instead of appending

echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo service haproxy restart
