#!/usr/bin/env bash
"" trsansfer files that passes four agruments""

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables from command-line arguments
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Perform the file transfer using scp
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
