#!/usr/bin/env bash
# Script to install and configure Nginx on an Ubuntu server

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is running and enabled on boot
sudo service nginx start
update-rc.d nginx defaults

# Replace the default index.html with "Holberton School"
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

sudo ufw allow 'Nginx HTTP'

# Restart Nginx 
sudo service nginx restart
