#!/usr/bin/env bash
# Configure a new Nginx server, with /redirect_me redirecting to another page.

# Update and install nginx
apt-get update
apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Set up the root directory and permissions
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create the default index.html
echo 'Hello World!' > /var/www/html/index.html

# Define the Nginx configuration to set up redirection
SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Redirection for /redirect_me to YouTube with a 301 Moved Permanently
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
}"

# Write the configuration to the default server block
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"

# Create a symbolic link to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# If the config is correct, restart Nginx to apply the changes
if [ $? -eq 0 ]; then
  # Restart Nginx to apply the configuration changes
  sudo service nginx restart
else
  echo "Nginx configuration test failed!"
  exit 1
fi
