#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me redirects to another page
# The redirection must be a "301 Moved Permanently"

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create necessary directories and files
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 http://google.com/;
    }

    error_page 404 /404.html;
}
EOF

# Reload Nginx to apply changes
sudo systemctl restart nginx
